apiVersion: v1
kind: Pod
metadata:
  name: myliveness-pod
spec:
  containers:
  - image: httpd:2.4
    imagePullPolicy: IfNotPresent
    name: myliveness-container

    command: ['sh', '-c', 'echo Container 1 is Running ; sleep 3600']

    ports:
    - name: liveness-port
      containerPort: 80
      hostPort: 8080

    livenessProbe:
      httpGet:
        path: /
        port: 80
      initialDelaySeconds: 2
      periodSeconds: 10