apiVersion: v1
kind: Pod
metadata:
  name: myapp-pod
  labels:
    name: myapp
spec:
  volumes:
    - name: myapp-pv-storage
      persistentVolumeClaim:
        claimName: myapp-pv-claim
  containers:
  - name: myapp-container
    image: nginx:latest
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
    - containerPort: 80
      name: "http-server"
    volumeMounts:
    - mountPath: "/usr/share/nginx/html"
      name: myapp-pv-storage
