apiVersion: v1
kind: Pod
metadata:
  name: pv-dynamic-pod
  labels:
    name: pv-dynamic-pod
spec:
  containers:
  - name: pv-dynamic-pod
    image: nginx
    resources:
      limits:
        memory: "128Mi"
        cpu: "500m"
    ports:
      - containerPort: 80
    volumeMounts:
      - mountPath: "/usr/share/nginx/html"
        name: html
  volumes:
  - name: pv-dynamic-storage
    persistentVolumeClaim:
      claimName: mypvc