apiVersion: v1
kind: PersistentVolume
metadata:
  name: myapp-pv
  labels:
    type: myapp
spec:
  storageClassName: manual
  capacity:
    storage: 5Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/home/course/git/TMS/HW_42/conf"
