apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-nginx
  namespace: default
spec:
  replicas: 2
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
      - name: nginx
        #image: 286665426170.dkr.ecr.us-east-2.amazonaws.com/nginx:latest
        image: public.ecr.aws/a3g6x2f2/nginx:latest
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---

apiVersion: v1
kind: Service
metadata:
  name: service-nginx
  labels:
    app: web
spec:
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
  selector:
    app: web
  type: LoadBalancer

