version: '3'
services:
  confluence:
    image: idalko/atlassian-confluence
    environment:
      - DISABLE_NOTIFICATIONS=TRUE
      - CONF_ARGS=-Datlassian.plugins.enable.wait=300
    volumes:
      - ./data:/opt/atlassian/confluence/data
    ports:
      - 8090:8090
    restart: always

  confluencedb:
    image: postgres:9.6
    environment:
      - POSTGRES_PASSWORD=secret
      - POSTGRES_USER=confluence
      - POSTGRES_DB=confluence
    volumes:
      - ./db:/var/lib/postgresql/data
    restart: always
